function createRandomWordList()
{
    var words = ['apprise',
    'finesse',
    'inundate',
    'encomium',
    'obfuscate',
    'coax',
    'skit',
    'noxious',
    'middling',
    'stanch',
    'countervail',
    'arabesque',
    'umbrage',
    'husk',
    'dissemble',
    'truce',
    'audacious',
    'shun',
    'brook',
    'extenuate',
    'clientele',
    'caustic',
    'abate',
    'forfeit',
    'precepts',
    'pundit',
    'duplicity',
    'imperviousness',
    'overhaul',
    'equanimity',
    'preclude',
    'antithetical',
    'vigilance',
    'procrastination',
    'enmity',
    'bellicose',
    'buoyant',
    'soot',
    'brittle',
    'poncho',
    'aplomb',
    'inculcate',
    'espouse',
    'hypocrisy',
    'astringent',
    'rave',
    'abrogate',
    'meretricious',
    'derision',
    'turpitude','abdicate',
    'abrasive',
    'abruptly',
    'acknowledge',
    'acquire',
    'addict',
    'adequate',
    'admonish',
    'affiliation',
    'agitate',
    'allege',
    'allocate',
    'alternative',
    'amendment',
    'antagonize',
    'attribute',
    'authentic',
    'bamboozle',
    'belligerent',
    'bewilder',
    'punctual',
    'bias',
    'boycott',
    'condor',
    'cause',
    'characterize',
    'chronological',
    'compel',
    'competent',
    'component',
    'conclusive',
    'concur',
    'condemn',
    'connotation',
    'consecutive',
    'irrelevant',
    'consult',
    'contrast',
    'copious',
    'correspond',
    'dawdle',
    'deceitful',
    'demeanor',
    'derogatory',
    'devastate',
    'devious',
    'devour',
    'diversity',
    'eligible',
    'emphasize',
    'estimate',
    'evaluate',
    'bewildered',
    'exposition',
    'exuberant',
    'famished',
    'formidable',
    'impartial',
    'indifferent',
    'industrious',
    'inevitable',
    'infuriate',
    'inhabitants',
    'initiate',
    'intimidate',
    'irate',
    'legendary',
    'liaison',
    'libel',
    'ludicrous',
    'mandatory',
    'mitigate',
    'naive',
    'narrate',
    'necessity',
    'negligent',
    'obnoxious',
    'omit',
    'opposition',
    'oppress',
    'perceive',
    'persuasive',
    'prediction',
    'prominent',
    'prospective',
    'exonerated',
    'quote',
    'relinquish',
    'resolve',
    'rudimentary',
    'signify',
    'sovereign',
    'suspense',
    'talisman',
    'tentative',
    'toxic',
    'treason',
    'viewpoint',
    'confront'
    ];

    var word = words[Math.floor(Math.random() * words.length)];
    return word
}

function getRandomWords()
{
    const word_list = []
    for (let i = 0; i < 11; i++) 
    {
        chosen_word = createRandomWordList();
        if (word_list.includes(chosen_word) == false) {
            word_list.push(chosen_word); 
        }
        
    }

    
    list = document.getElementById("wordList");
    list.innerHTML = ''

    word_list.forEach(element => {
        let li = document.createElement("li");
        li.innerText = element;
        list.appendChild(li);
    });
}
